### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by fman028** [MYOB-Technology/myob_accountright_sample_nodejs#3]
I follow the instructions to start the app, but I get:

c:\ws\myob_accountright_sample_nodejs\app.js:34
  var MemoryStore = require('connect').session.MemoryStore;
                                              ^
TypeError: Cannot read property 'MemoryStore' of undefined

Any ideas?

**Comment by fman028** [comment]
Updated app.js to use express-session, and got it working.

**Comment by sawilde** [comment]
awesome - please feel free to submit it back - the sample is quite old so needed some more recent care like you have given it.

**Comment by fman028** [comment]
Cool, I tried committing and making a pull request yesterday, but ran into some authentication issues.  I'll give it another go now.
